spring.application.name=OnlineExaminationSystem

# ? LIVE AIVEN CLOUD MYSQL ROUTING WITH EXPLICIT SSL ENFORCEMENT
spring.datasource.url=jdbc:mysql://mysql-35d27f2-ambigyashavanth-1e5e.aivencloud.com:10532/defaultdb?sslMode=VERIFY_IDENTITY&allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_FC7k-mcmCJg-zEMPvCF

# JPA / Hibernate Lifecycle Rules
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Runtime Parameters
server.port=8080